<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<title><?php echo $this->path; ?></title>

	<script type="text/javascript" src="imagevue/javascript/window.js"></script>
	<script type="text/javascript" src="imagevue/javascript/prototype.js"></script>
	<style type="text/css">
	<!--
	* { margin:0; padding:0 }
	body {
		background-color: #FFFFFF;
		margin: 0px;
		padding: 10px;
	}
	.od {
		position: absolute;
		left: 0px;
		top: 0px;
		width:100%;
		text-align:right;
		-moz-opacity: .5;
		filter: alpha(opacity=50);
		visibility:hidden;
	}
	.id {
		float:right;
		background-color:#FFFFFF;
		margin: 20px;
		padding: 10px;
		font-family:Verdana, Arial, Helvetica, sans-serif;
		font-size: 13px;
		font-weight: bold;
		border: dashed 1px #FFFFFF;
	}
	a:link {
		color: #000000;
		text-decoration: none;
	}
	a:visited {
		text-decoration: none;
		color: #000000;
	}
	a:hover {
		text-decoration: none;
		color: #000000;
	}
	a:active {
		text-decoration: none;
		color: #000000;
	}
	-->
	</style>
</head>

<body onload="resizetoimage();">

	<a href="javascript:window.close()" onmouseover="$('closelayer').setStyle({visibility: 'visible'});" onmouseout="$('closelayer').setStyle({visibility: 'hidden'});"><img src="<?php echo $this->path; ?>" alt="<?php echo $this->path; ?>" border="0">
	<div id="closelayer" class="od"><div class="id">关闭&nbsp;[x]</div></div></a>

</body>
</html>