<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<title><?php echo $this->siteTitle; ?></title>
		<link href="<?php echo IV_PATH; ?>css/forAdmin.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo IV_PATH; ?>css/forImagevue.css" rel="stylesheet" type="text/css" />
		<meta name="description" content="<?php echo $this->siteTitle; ?> gallery" />
		<meta http-equiv="Content-Type" content="text/html" />
		<script type="text/javascript" src="<?php echo IV_PATH; ?>javascript/swfobject.js"></script>
		<script type="text/javascript" src="<?php echo IV_PATH; ?>javascript/swfaddress.js"></script>
		<style type="text/css">
			* { margin: 0; padding: 0; }
			html { height: 100%; }
			table { border-collapse: collapse;}
			#imagevue { height: 100%; }
			body { 	background-color: #<?php echo $this->bkGrColor; ?>;
					height: 100%; line-height: 0px;}
		</style>
	</head>
	<body>
		<table height="100%" width="100%">
		<!-- #forAdmin -->	
		<?php if (ivAcl::isAdmin()): ?>
			<tr>
				<td>
					<div id="forAdmin">
						<div class="right"><?php echo htmlspecialchars(ivAuth::getCurrentUserLogin()) ?>
							<a href="imagevue/?c=cred&amp;a=logout" title="注销并关闭管理工具栏">关闭 &raquo;</a>
						</div>
						<a id="editPageLink" href="imagevue/?path=<?php echo $this->placeholder->get('currentPath'); ?>" title="相册管理/文件管理">编辑该页 &raquo;</a> 
						<a id="htmlVersionLink" href="?<?php echo $this->placeholder->get('currentPath'); ?>" title="此页面的 HTML 版本">HTML 版本 &raquo;</a> 
						<a id="makeThumbsLink" href="imagevue/?a=makethumbs&amp;path=<?php echo $this->placeholder->get('currentPath'); ?>" title="重建该目录或这张图片的缩略图">重建缩略图 &raquo;</a>
						<a href="imagevue/?c=config" title="更改 <?php echo $this->siteTitle; ?> 设置">设置 &raquo;</a> 
						<!-- <a href="?a=index">API Reference &raquo;</a>  -->
					</div>
					<script type="text/javascript">
					//<![CDATA[
						SWFAddress.addEventListener(SWFAddressEvent.CHANGE, function(event) {
							var path = SWFAddress.getPath().substr(1);
							document.getElementById('editPageLink').href = 'imagevue/?path=' + path;
							document.getElementById('htmlVersionLink').href = '?' + path;
							var makeThumbsLink = document.getElementById('makeThumbsLink');
							if (/[^\/]+\.[^\/]+\/$/.test(path)) {
								makeThumbsLink.style.display = 'none';
							} else {
								makeThumbsLink.style.display = '';
								makeThumbsLink.href = 'imagevue/?a=makethumbs&path=' + path;
							}
						});
					// ]]>
					</script>
				</td>
			</tr>
			<?php endif; ?>
			<!-- /forAdmin -->
			<tr>
				<td height="100%">
	 				<div style="height: 100%">
						<div id="imagevue">
							<div id="na">
								<div id="notice">
									<h1>
										哎呦! - 该页面需要开启JavaScripts
									</h1><br>
									请在您的浏览器中启用JavaScripts并重新加载本页.<br>
									&raquo; <a href="?p=gallery">Flash 相册</a><br>
									<br>
								</div><?php if ($this->enabledHTML): ?>你可以选择访问HTML相册页面:<br>
								&raquo; <a href="?p=html">HTML 相册</a><br>
								&raquo; <a href="?p=sitemap">HTML 站点地图</a><br>
								<br>
								<?php endif; ?>相册汉化 by:<br>
								&raquo;
								<h1>
									小超</h1>								</h1>
							</div>
						</div>
					</div>

					<script type="text/javascript">
					//<![CDATA[
						<?php if (count($this->vars)): ?>
							var flashVars = {
								foreground_color: '<?php echo $this->frGrColor; ?>',
								background_color: '<?php echo $this->bkGrColor; ?>'
							};
							<?php foreach ($this->vars as $key => $value): ?>
								flashVars.<?php echo $key; ?> = '<?php echo $value; ?>';
							<?php endforeach; ?>
						<?php endif; ?>

						swfobject.embedSWF("<?php echo IV_PATH; ?>imagevue2.swf", "imagevue", "100%", "100%", "8.0.0", "<?php echo IV_PATH; ?>expressInstall.swf", flashVars, {allowScriptAccess: 'always', allowFullScreen: true, bgcolor: '#<?php echo $this->bkGrColor; ?>'}, {id: 'imagevue', name: 'imagevue'});
					// ]]>
					</script>
				</td>
			</tr>
		</table>
		<!-- UY BEGIN -->
<div id="uyan_frame"></div>
<script src="http://s11.cnzz.com/stat.php?id=4561667&web_id=4561667" language="JavaScript"></script>
<script type="text/javascript" id="UYScript" src="http://v1.uyan.cc/js/iframe.js?UYUserId=1699342" async=""></script>
<!-- UY END -->
<script>
function turn(){
setTimeout("window.scroll(0,document.body.scrollTop+900)");
}
</script>
	</body>
</html>
