<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?php
	$conf = &ivPool::get('conf');
	$siteTitle = $conf->get('/config/imagevue/settings/sitetitle');
	$currentTitle = $this->placeholder->get('currentTitle');
	$swfAPath = $this->placeholder->get('currentPath');
	if (substr($swfAPath,-1) != '/') {
		$swfAPath .= '/';
	}
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="viewport" content="width=640" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<title><?php echo $siteTitle; ?> <?php echo $currentTitle; ?></title>
		<link href="<?php echo IV_PATH; ?>css/dtree.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo IV_PATH; ?>css/htmlstyle.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo IV_PATH; ?>css/htmlstyle.css" rel="stylesheet" type="text/css" />
		<link media="only screen and (max-device-width: 480px)" href="<?php echo IV_PATH; ?>css/forIphone.css" type="text/css" rel="stylesheet" />
		<?php if (!empty($_COOKIE['stylesheet'])): ?>
			<link href="<?php echo IV_PATH; ?>css/<?php echo $_COOKIE['stylesheet']; ?>" rel="stylesheet" type="text/css" />
		<?php endif; ?>
		<link href="<?php echo IV_PATH; ?>css/forAdmin.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?php echo IV_PATH; ?>javascript/dtree.js"></script>
		<script type="text/javascript" src="<?php echo IV_PATH; ?>javascript/prototype.js"></script>
		
		<!-- lightbox2 http://www.lokeshdhakar.com/projects/lightbox2/ -->
		<script type='text/javascript' src='<?php echo IV_PATH; ?>lightbox/js/scriptaculous.js?load=effects,builder'></script>
		<script type="text/javascript" src="<?php echo IV_PATH; ?>lightbox/js/lightbox.js"></script>
		<link rel="stylesheet" href="<?php echo IV_PATH; ?>lightbox/css/lightbox.css" type="text/css" media="screen" />
	</head>
	<body>
		<?php if (ivAcl::isAdmin()): ?>
			<!-- #forAdmin -->	
			<div id="forAdmin">
				<div  class="right"><?php echo htmlspecialchars(ivAuth::getCurrentUserLogin()) ?>
					<a href="imagevue/?c=cred&amp;a=logout" title="注销并关闭管理工具栏">关闭 &raquo;</a>
				</div>
				<a href="imagevue/?path=<?php echo urlencode($this->placeholder->get('currentPath')); ?>" title="相册管理员/文件管理">编辑该页面 &raquo;</a> 
				<a href="?p=gallery#/<?php echo $swfAPath; ?>" title="此页面的 Flash 版本">Flash 版本 &raquo;</a> 
				<?php $thumbRecreationPath = $this->placeholder->get('thumbRecreationPath'); ?>
				<?php if ($thumbRecreationPath): ?>
					<a href="imagevue/?a=makethumbs&amp;path=<?php echo $thumbRecreationPath; ?>" title="重建该目录的缩略图">重建缩略图 &raquo;</a> 
				<?php endif; ?>
				<a href="imagevue/?c=config" title="更改 <?php echo $siteTitle; ?> 设置">设置 &raquo;</a> 
				<!-- <a href="?a=index">API Reference &raquo;</a>  -->
			</div>
			<!-- /forAdmin -->
		<?php endif; ?>

		<!-- #header -->
		<div id="header"><?php echo $siteTitle; ?></div>
		<!-- /header -->

		<!-- #subheader -->
		<div id="subheader">

			<div id="flashlink">
				<a href="?p=gallery#/<?php echo $swfAPath; ?>" title="此页面的 Flash 版本" target="_blank">Flash 版本 &raquo;</a>
			</div>

			<div id="menu">
				<div>
					<img src="imagevue/images/plus_icon.png" alt="" class="openMenu"/>
				</div>
				<!-- JSTREE STARTS HERE -->
				<?php echo $this->placeholder->get('tree'); ?>
				<!-- JSTREE ENDS HERE -->
			</div>

			<div class="crumbs">
				<?php $brCrumbs = &ivPool::get('breadCrumbs'); ?>
				<?php foreach ($brCrumbs->get() as $crumb): ?>                                  
					<a class="<?php echo $crumb->className; ?>" href="<?php echo $crumb->url; ?>"><?php echo $crumb->title; ?></a><?php echo $crumb->suffix; ?><?php echo ($brCrumbs->tail() === $crumb->title ? '' : '&raquo;'); ?>
				<?php endforeach; ?>
			</div>

			<div class="clrFlt"></div>
		</div>
		<!-- /subheader -->

		<div id="content">
			<?php echo $this->getPageContent(); ?>
		</div>
	</body>
</html>