<?php
	$function = create_function('$path', "return trim(preg_replace('/\W/', '_', \$path), '_');");
	$firstLevelItems = array();
	foreach ($this->flatConfig as $itemInfo) {
		if (2 == $itemInfo['depth']) {
			$firstLevelItems[$itemInfo['node']->getName()] = call_user_func($function, $itemInfo['path']);
		}
	}
?>
<div id="content">
	<div id="rightmenu">
<!--
		<div class="box">
			<div class="heading ivrm" id="config_content">Languages</div>
			<div class="content actions">
				<br />
			</div>
		</div>
-->
	</div>
	<div id="leftcontent">  
		<p>
			<?php $lastFirstLevelItem = end($firstLevelItems); ?>
			<?php foreach ($firstLevelItems as $name => $id): ?>
				<a href="#<?php echo $id ?>">
					<?php echo ucfirst($name); ?>
				</a>
				<?php if ($lastFirstLevelItem != $id): ?>
					|
				<?php endif; ?>
			<?php endforeach; ?>
		</p>
		<form method="post" action="">
			<p>
				<input type="submit" name="save" value="保 存" />
				<input type="button" value="全部展开" onclick="$$('.ivconf').each(function (el) {el.addClassName('open'); el.next().show();});" />
				<input type="button" value="全部折叠" onclick="$$('.ivconf').each(function (el) {el.removeClassName('open'); el.next().hide();});" />
			</p>
			<div id="config">
				<div id="formtree">
					<?php $oldDepth = 0; ?>
					<?php $id = 1; ?>
					<?php foreach ($this->flatConfig as $itemInfo): ?>
						<?php if (1 < $itemInfo['depth']): ?>
							<?php if ($oldDepth > $itemInfo['depth']): ?>
								<?php for ($i = 0; $i < $oldDepth - $itemInfo['depth']; $i++): ?>
									</div>
								</div>
								<?php endfor; ?>
							<?php endif; ?>
							<?php if ($itemInfo['node']->hasChildren()): ?>
								<?php $aId = call_user_func($function, $itemInfo['path']); ?>
								<?php $opened = in_array($aId, $this->openedPanels); ?>
								<a href="#" id="<?php echo $aId; ?>" class="ivconf <?php echo $opened ? 'open' : ''; ?>" onclick="return false;"><?php echo $itemInfo['node']->getName(); ?></a>
								<div class="subitems"<?php echo $opened ? '' : ' style="display: none;"'; ?>>
									<div class="itemgroup">
							<?php else: ?>
								<div class="item" id="l<?php echo $id ?>">
									<div class="help"  style="float:right; text-align: right; width: 60%;" id="h<?php echo $id ?>">
										<?php echo $itemInfo['node']->getAttribute('description'); ?>
									</div>
									<div style="float: left">
									   <?php echo $itemInfo['node']->getName(); ?>:<br />
									   <?php echo $itemInfo['node']->toFormElement("config[{$itemInfo['path']}]", $id); ?>
									</div>
								</div>
							<?php endif; ?>
						<?php endif; ?>
						<?php $oldDepth = $itemInfo['depth']; ?>
						<?php $id++; ?>
					<?php endforeach; ?>
					<?php for ($i = 0; $i < $oldDepth - 2; $i++): ?>
						</div>
					</div>
					<?php endfor; ?>
				</div>
			</div>
			<div> 
				<input type="submit" name="save" value="保 存" />
				<input type="button" value="全部展开" onclick="$$('.ivconf').each(function (el) {el.addClassName('open'); el.next().show();});" />
				<input type="button" value="全部折叠" onclick="$$('.ivconf').each(function (el) {el.removeClassName('open'); el.next().hide();});" />
			</div>
		</form>
	</div>
</div>