<div id="content">
	<div id="rightmenu">
		<div class="box">
			<div id="diagnostic_page" class="heading ivrm">诊断页面</div>
			<div class="content actions">
				<a class="myicon" href="index.php?c=diag&amp;a=index">文件系统诊断页</a>
				<a class="myicon" href="index.php?c=diag&amp;a=errors">错误诊断页面</a>
				<a class="myicon" href="index.php?c=diag&amp;a=phpinfo">PHP信息</a>
			</div>
		</div>
	</div>
	
	<div id="leftcontent">
		<table  class="diagnostics">
			<tr>
				<th width="100%">模块名称</th>
				<th>&nbsp;</th>
			</tr>
			<?php foreach ($this->modules as $module): ?>
				<tr onmouseout="$(this).style.backgroundColor = '';" onmouseover="$(this).style.backgroundColor = '#333';">
					<td><?php echo $module; ?></td>
					<?php if (isset($this->badModules[$module])): ?>
						<td align="center">
							<a name="error"></a>
							<img src="images/admin/icon_error.gif" alt="" />
						</td>
						<td><?php echo $this->badModules[$module] ?>"</td>
					<?php else: ?>
						<td align="center">
							<img src="images/admin/icon_ok.gif" alt="" />
						</td>
						<td>&nbsp;</td>
					<?php endif; ?>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>
</div>